version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=Kumamon3
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  server:
    build:
      context: "./server"
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=album_store
      - DB_PASSWORD=Kumamon3
      - DB_PORT=5432
  client:
    stdin_open: true
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
